import React, { useCallback } from 'react';

import SitePage from './SitePage';
import getAllLayouts from '@/api/get-all-layouts';
import getLayoutByID from '@/api/get-layout-by-id';
import { Transition } from '@headlessui/react';
import { Metadata } from 'next';
export async function generateStaticParams() {
  const layouts = await getAllLayouts().then((res) => res);
  const paths = layouts?.map((layout) => ({
    slug: layout?._id,
  }));
  return paths;
}
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
//   viewport: 'width=device-width, initial-scale=2, maximum-scale=1', // <-- here
// };
export default async function Page({ params }: { params: { slug: string } }) {
  const { slug } = params;
  const res = await getLayoutByID(slug);
  return <SitePage sites={res} />;
}
