import React, { useCallback } from 'react';

import SitePage from './SitePage';
import getAllLayouts from '@/api/get-all-layouts';
import getLayoutByID from '@/api/get-layout-by-id';
import { Transition } from '@headlessui/react';
import { Metadata } from 'next';
export async function generateStaticParams() {
  const layouts = await getAllLayouts().then((res) => res);
  return (
    layouts.map((layout) => ({
      slug: layout?._id,
    })) || []
  );
}
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=2, maximum-scale=1', // <-- here
};
export default async function Page({ params }) {
  const { slug } = params;
  const site = await getLayoutByID(slug);
  return <SitePage site={site} />;
}
