

const OBJECT_NOT_FOUND = "OBJECT_NOT_FOUND"
const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
const BAD_REQUEST = "BAD_REQUEST"
const SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG"
const UNAUTHORISED = "UNAUTHORISED"
const OBJECT_ALREADY_EXISTS = "OBJECT_ALREADY_EXISTS"
const OBJECT_USER_INACTIVATED = "OBJECT_USER_INACTIVATED";
const OBJECT_USER_ACTIVATED = "OBJECT_USER_ACTIVATED";

export { OBJECT_ALREADY_EXISTS,BAD_REQUEST, INTERNAL_SERVER_ERROR, OBJECT_NOT_FOUND,SOMETHING_WENT_WRONG,UNAUTHORISED, OBJECT_USER_INACTIVATED, OBJECT_USER_ACTIVATED}

