

const OBJECT_NOT_FOUND = "OBJECT_NOT_FOUND"
const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
const BAD_REQUEST = "BAD_REQUEST"

export { BAD_REQUEST, INTERNAL_SERVER_ERROR, OBJECT_NOT_FOUND }

