name: Deploy Backend

on:
    push:
        paths:
            - "server/**"
        branches:
            - "*"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Check if changes are in "server" directory
              id: check_changes
              run: |
                  CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

                  # Check if any of the changed files are in the "server" directory
                  if echo "$CHANGED_FILES" | grep -qE '^server/|^server-*/'; then
                    echo "::set-output name=changes::true"
                  else
                    echo "::set-output name=changes::false"
                  fi

            - name: SSH and deploy
              if: steps.check_changes.outputs.changes == 'true'
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              run: |
                  echo "$SSH_PRIVATE_KEY" > keyfile
                  chmod 600 keyfile
                  mkdir -p ~/.ssh
                  cp known_hosts ~/.ssh/known_hosts
                  ssh -t -i keyfile ubuntu@13.232.88.16 "bash ~/deploy.sh"
